api:
  build: .
  dockerfile: Dockerfile
  env_file: .env
  command: mix phoenix.server
  environment:
    - MIX_ENV=dev
    - PORT=4000
    - DATABASE_POSTGRESQL_HOSTNAME=postgres
    - DATABASE_POSTGRESQL_USERNAME=postgres
    - DATABASE_POSTGRESQL_PASSWORD=postgres
  volumes:
    - .:/app
  ports:
    - "4000:4000"
  links:
    - postgres

test:
  image: backend_api
  env_file: .env
  command: mix test
  environment:
    - MIX_ENV=test
    - PORT=4001
    - DATABASE_POSTGRESQL_HOSTNAME=postgres
    - DATABASE_POSTGRESQL_USERNAME=postgres
    - DATABASE_POSTGRESQL_PASSWORD=postgres
  volumes_from:
    - api
  links:
    - postgres

postgres:
  image: postgres:9.6 # https://hub.docker.com/_/postgres/
  ports:
    - "5432"
